VAS/Areas/VAS/Content/VPaySelect.css
VAS/Areas/VAS/Scripts/app/forms/acctviewer.js

Changes is in Css file and AccViewer.js only

Button CSS issue fixed

---

ModelLibrary/Model/MAsset.cs
ModelLibrary/Model/MInventory.cs
ModelLibrary/Model/MInventoryLine.cs

Work done for Asset Capital/Expenses.

Set Equipment Category on Asset from Product and Product Category.

---

VAS/Areas/VAS/Scripts/app/forms/vcreatefromrequisition.js
VASLogic/Models/VCreateFromModel.cs

Handle issue on search by Product.

Show message on form after submit

---

ModelLibrary/Classes/CostingCheck.cs
ModelLibrary/Model/MCostDetail.cs
ModelLibrary/Model/MCostQueue.cs
ModelLibrary/Process/ReCostingCalculation.cs

handle Physical Inventory price with multi-currency Accounting Schema

handle Treat as discount with multiple Accounting Schema

---

ModelLibrary/Model/MCostDetail.cs
ModelLibrary/Model/MCostQueue.cs
ModelLibrary/Model/MInvoice.cs
ModelLibrary/Model/MLandedCost.cs
ModelLibrary/Model/MPayment.cs

DevOps Task ID: 2111 - Cost Adjustment on Product Cost after Actual Invoice wrt Quantity availablity against the GRN linked with Invoice
Handle Save Issue on Landed cost whenselect only product

DevOps Task ID: 2107 - Payment cant not be created with ZERO amount

---

ModelLibrary/Model/MRequest.cs

Time in the Date next action field is calculated and Changed the value of result.

Bug Id 2105:

---

ModelLibrary/Model/MInvoicePaySchedule.cs
ModelLibrary/Model/MPayment.cs

System will not mark invoice scehdule as paid when amount is negative and linked order is POS type

 DevOps Task ID - 2121

---

ModelLibrary/Model/MInvoice.cs
ModelLibrary/Model/MMatchInv.cs
ModelLibrary/Process/InventoryRevaluation.cs

DevOps Task ID: 2152: Matched Invoice Price

DevOps Task ID - 2151: Inventory Revaluation

---

ModelLibrary/ModelLibrary.csproj
ModelLibrary/Process/CreateRecurringFromGLJournal.cs
ModelLibrary/Process/CreateRecurringFromGLJournalBatch.cs
ModelLibrary/Process/CreateRecurringFromInvoice.cs

Recurring Utility Enhancement

---

VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

VAI055 Alert SQL Generator

---

ModelLibrary/Model/MOrder.cs
ModelLibrary/Model/MVASContractLine.cs
ModelLibrary/Process/PublishContract.cs
ModelLibrary/Process/ReActiveContract.cs
ModelLibrary/Process/RenewalContract.cs
VAS/Areas/VAS/Scripts/model/VAS_CalloutContract.js

2.Renewal Date should not be greater than current date. & Amount Should be greater than Utilize amount of contract.
3. In sales order set Line Total Amount  zero on Void.

1.Freeze tabs in ContractMaster on Publish & Unfreeze on Reactivate .

---

ModelLibrary/Process/ProfitLossClosing.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/_layouts/15/Doc.aspx?sourcedoc=%7B8D14E08D-CA32-4967-9F21-FD8E47789A03%7D&file=CodingChecklist_Official_VAStandard(VAS)_Above_1.2.15.0(1).docx&action=default&mobileredirect=true)
DevOps ID [3355](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/3355)

DevOps Task ID: 3355, Resolve point of Generate Line on Profit and Loss

---

ModelLibrary/Model/MInvoice.cs
ModelLibrary/Model/MOrder.cs
ModelLibrary/Process/ApplyDiscountOnOrder.cs
VAS/Areas/VAS/Scripts/model/calloutorderline.js

2.Show message when user did not apply the discount and tries to clear the discount. 3.Show message when user apply the discount without inserting the lines

1.Set product and charge null for contract line callout.

---

ModelLibrary/Model/MCostElementLine.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_VAS_Official-VAStandard-ERP_CRM(VAS)_Above_1.2.15.0(6).docx?d=wb7914e825eeb4a0585927044a80fae2d&csf=1&web=1&e=4TbXXI)
[3460](http://130.61.149.181/ViennaAdvantage/_search?text=3460&type=workitem&lp=custom-Collection)

BugId-3460: Add "W" in the query to handled the Weighted Average Cost issue.

---

VASLogic/Models/PaymentAllocation.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.2.15.0.docx?d=w8f6f69aa9cc249b6b7c6d72cd8c1c4ec&csf=1&web=1&e=bZmcbV)
[3417](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_dashboards/dashboard/2e84a1e3-c9d3-4ba7-a9ef-7884cd6e356b)

BugId 3417 handled allocation of ARC With GL JournalLine

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Controllers/AlertSQLGenerateController.cs
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

Bug fix of Alert SQL Generator

Vai055 sql generator

---

ModelLibrary/Model/MJournal.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.2.16.0%20(1).docx?d=w3008a612dc394e7fb982b226ed822008&csf=1&web=1&e=mNkaMs)
[3199](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_dashboards/dashboard/2e84a1e3-c9d3-4ba7-a9ef-7884cd6e356b)

BugId 3199 handled transaction for non-business day

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js

Implemented column checkbox filtration issue

Implemented column checkbox filtration issue

---

ModelLibrary/Model/MCostQueue.cs
ModelLibrary/Model/MInvoiceLine.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B76670614-8f7a-45c6-bef0-7857604dc6cf%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk_ns.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1703146135284&web=1)
[3605](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_boards/board/t/Finance/Backlog%20items)

Task ID-3605, Allow expected Landed Cost in different currency.

---

VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js

Made Table/column editable in filtration

Made Table/column editable in filteration

---

ModelLibrary/Model/MInvoiceLine.cs

[Coding CHecklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_VAS_Official-VAStandard-ERP_CRM(VAS)_Above_1.2.17.6.docx?d=w021187c9f8dc4911ae5ed7016eeb5f1f&csf=1&web=1&e=HTFoWL)
[811](http://130.61.149.181/ViennaAdvantage/_search?text=811&type=workitem&lp=custom-Collection)

Handled the Case when user will delete Invoice line. Order field in Invoice tab will be updated according to order  in Invoice line.

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

Changed Left Join As Left Outer Join

Changed Left Join As Left Outer Join

---

VAS/Areas/VAS/Scripts/model/calloutinvoice.js

On change of quantity, price should be set based on discount schema.
[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/Coding%20Checklist_Official-VAStandard-ERP-CRM_Above_1.2.16.0.docx?d=w3b9c76a81cc84e40b9dcbcd351a15daf&csf=1&web=1&e=DNsDNz)
[DevOps ID:4092](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/4092)

Handle Price issue on AP Invoice:-

---

VAS/Areas/VAS/Content/PoReceiptTabPanel.css
VAS/Areas/VAS/Controllers/PoReceiptController.cs
VAS/Areas/VAS/Scripts/app/forms/PoReceiptTabPanel.js
VAS/Areas/VAS/VASAreaRegistration.cs
VASLogic/Models/PoReceiptTabPanelModel.cs

[CodingChecklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_VAS_Official-VAStandard-ERP-CRM(VAS)_Above_(1.2.16.0).docx?d=we4a3c0c9b72343188c144019aaa0c4c9&csf=1&web=1&e=5D886U)
[4216](http://130.61.149.181/ViennaAdvantage/_search?text=4216&type=workitem&lp=custom-Collection)

Devops ID: 4216 Create Tab Panel on Invoice Line for Matched Po and Receipt

---

VAS/Areas/VAS/Content/PoReceiptTabPanel.css
VAS/Areas/VAS/Controllers/PoReceiptController.cs
VAS/Areas/VAS/Scripts/app/forms/InvoiceTaxTabPanel.js
VASLogic/Models/PoReceiptTabPanelModel.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/[CodingChecklist_Official_VAStandard(VAS)_Above_1.2.16.0(4).docx](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.2.16.0(4).docx?d=w6b6fc2094293479e82be708662850451&csf=1&web=1&e=I2sbv1)?d=w6b6fc2094293479e82be708662850451&csf=1&web=1&e=I2sbv1)
[4261](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_search?text=4261&type=workitem&lp=dashboard-Project&filters=Projects%7BStandard%20ERP-CRM%7D)

Devops ID: 4261 Created tab panel on Invoice tab to get Invoice tax data

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Controllers/AlertSQLGenerateController.cs
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js

Refresh filtration of checkboxes and add LIKE operator

Refresh filtration of checkboxes and add LIKE operator

---

ModelLibrary/ModelAD/MSetup.cs
ModelLibrary/Process/DocumentTypeVerify.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/_layouts/15/Doc.aspx?sourcedoc=%7B2269E717-576F-45BE-8A43-966B42B1E790%7D&file=CodingChecklist_Official_VAStandard(VAS)_Above_1.2.17.0.docx&action=default&mobileredirect=true)
[4681](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_boards/board/t/Finance/Backlog%20items)

Task ID: 4681,Handle Tenant creation process point for PostgreSQL

---

ModelLibrary/Model/MAllocationLine.cs
ModelLibrary/Model/MPayment.cs
VAS/Areas/VAS/Scripts/app/forms/vallocation.js
VASLogic/Models/PaymentAllocation.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.2.17.0%20(1).docx?d=w3e02bde396ae41feb86a8f931a903b5d&csf=1&web=1&e=iRPWnv)
[4680](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_dashboards/dashboard/2e84a1e3-c9d3-4ba7-a9ef-7884cd6e356b)

DevopsId 4680 Done enhancement to set unallocated amount on Payment tab

---

ModelLibrary/Model/MVASContractMaster.cs
ModelLibrary/Process/RfQResponseCComplete.cs
ModelLibrary/Process/RfQResponseRank.cs

2.On Vendor Response When user click on check complete  than child tabs should be freezed. 3.If Contract Line exist than user can not change Contract start date and end date on header.

1.Handled the issue that Showing Wrong ranking on header.

---

VASLogic/Models/PaymentAllocation.cs

[CodingChecklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/_layouts/15/Doc.aspx?sourcedoc=%7B18133852-74C2-4FAF-8022-229BFEAED5F9%7D&file=CodingChecklist_VAS_Official-VAStandard-ERP-CRM(VAS)_Above_(1.3.2.0).docx&action=default&mobileredirect=true)
[5041](http://130.61.149.181/ViennaAdvantage/_search?text=5041&type=workitem&lp=custom-Collection)

Devops Id: 5041 The Invoice Schedule is not shown on the payment allocation form after the Allocation Document is in Progress.

---

VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

Refresh Alert SQL generator tab panel when no record found.
Devops Id: [4760](http://130.61.149.181/ViennaAdvantage/Framework/_workitems/edit/4760)
[CodingChecklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/VAFramework/_layouts/15/Doc.aspx?sourcedoc=%7B6150BC9F-503B-473E-B38F-691D1BDDE365%7D&file=CodingChecklist_AlertRefreshTabPanel_16Feb2024.docx&action=default&mobileredirect=true)

Refresh SQL Generator tab panel when no record found.

---

ModelLibrary/ModelAD/MOrg.cs
ModelLibrary/Process/CreateContractInvoice.cs

[Coding checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard-ERP-CRM(VAS)_Above_1.3.2.0.docx?d=wb6c5bd085a91423592f6b87e42e65208&csf=1&web=1&e=gWZlV3)
[DevOps ](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/5142)

Vai082 check org access

---

VAS/Areas/VAS/Controllers/OrderLineTabPanelController.cs
VAS/Areas/VAS/Scripts/app/forms/MatchPOTabPanel.js
VAS/Areas/VAS/Scripts/app/forms/RequisitionLinesTabPanel.js
VAS/Areas/VAS/VASAreaRegistration.cs
VAS/VAS.csproj
VASLogic/Models/OrderLineTabPanelModel.cs
VASLogic/VASLogic.csproj

Added Match PO and Reuisition Lines Tab Panel on PO Lines  tab of

---

VASLogic/Models/Callouts/MConversionRateModel.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/Coding%20Checklist_VAS_Above_1.3.2.0%20-%20Amit.docx?d=wfb5369d3c802452ba686515a09014a35&csf=1&web=1&e=nQNI3B)

Handle Conversion date based on UTC

---

ModelLibrary/Process/RfQCreate.cs
VAS/Areas/VAS/Content/PoReceiptTabPanel.css
VAS/Areas/VAS/Scripts/app/forms/MatchPOTabPanel.js
VAS/Areas/VAS/Scripts/app/forms/RequisitionLinesTabPanel.js
VASLogic/Models/OrderLineTabPanelModel.cs

RFQ tab of RFQ Window.
2.Handled Precision Line Amount  and Unit Price on Requisition Tab Panel 3.Handled Duplication of data on Requisition and Match PO Tab Panel 4.Handled Qty format on Match PO  and Requisition Tab Panel 5.Handled Design for Product , Charge and Set attribute instance on Match PO  and Requisition Tab Panel

1.Set Published Checkbox true when click on Publish and Invite Button on

---

ModelLibrary/Model/MUOMConversion.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/Coding%20Checklist_VAS_Above_1.3.2.0%20(UOM)-%20Amit.docx?d=waec4ba01ad494db5a94616ba70ff8f28&csf=1&web=1&e=N4Ud1f)
[5553](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_boards/board/t/Finance/Backlog%20items)

System will allow to save the UOM conversion rate from bigger to smaller rate.

---

ModelLibrary/Model/MCostDetail.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/Coding%20Checklist_VAS_Above_1.3.2.0%20(Costing)-%20Amit.docx?d=w49e94011129a4c61ba13620cd16c114c&csf=1&web=1&e=FGvwd1)
[5552](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_boards/board/t/Finance/Backlog%20items)

Calculate Cost Combination on consumption when costing method is linked with LIFO / FIFO

---

ModelLibrary/Model/MConversionRate.cs
ModelLibrary/Process/CalculateCrossCurrRate.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/Coding%20Checklist_VAS_Above_1.4.3.0%20-%20Amit.docx?d=wd253ffab92824e9b8a60d91d1823c4c7&csf=1&web=1&e=96LPjm)
[5703](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/myactivity/)

DevOps ID: 5703, System will creates Cross Currency rate entry automatically based on cross rate setting when user create conversion rate.

---

VAS/Areas/VAS/Controllers/VAS_TimeSheetInvoicesController.cs
VAS/Areas/VAS/Scripts/app/forms/VAS_TimeSheetInvoice.js
VASLogic/Models/VAS_TimeSheetInvoice.cs

[Coding CheckList](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/[CodingChecklist_Official_VAStandard(VAS)_Above_1.4.4.0.docx](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.4.4.0.docx?d=wd8615841d9324073bd2babe46e3cde83&csf=1&web=1&e=ROWXNV)?d=wd8615841d9324073bd2babe46e3cde83&csf=1&web=1&e=ROWXNV)
[5719](http://130.61.149.181/ViennaAdvantage/_search?text=5719&type=workitem&lp=custom-Collection)

Handled the phase design and messge issue

---

ModelLibrary/Model/MAlert.cs
VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

We need to differentiate the SQl/SQL Generate and Test SQL and Save SQL with color.
SQL generator should be first
Apply multiple color in joins and condition
Display Common columns for joins.
Save Alert handler in AD_Alert on basis of Ad_schedule_ID
Role Check on window/tab for Sql Generator.
[Coding Checklist_AlertUIFixes](https://github.com/VIENNA-Advantage-ERP-CRM/Official-VAStandard-ERP-CRM/files/15259036/Coding.Checklist_AlertUIFixes._09May2024.docx)

Alert UI Fixes

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Scripts/app/forms/VAS_TimeSheetInvoice.js

1.Replaced the Refresh name with the Refresh icon. 2.Placed  the refresh icon on top before the dynamic filter icon. 3.Placed the Document Type field, Preview, and Generate AR Invoice buttons on the bottom.
[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/[CodingChecklist_Official_VAStandard(VAS)_Above_1.4.4.0(3).docx](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.4.4.0(3).docx?d=wd0ee3218b1924433a39c34b332fec6ce&csf=1&web=1&e=4PQ6Kj)?d=wd0ee3218b1924433a39c34b332fec6ce&csf=1&web=1&e=4PQ6Kj)

Handled the below points:

---

VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js

1. Add on top selected checkboxes.
2. Filter operator on basis of column datatype.
3. Autofill common key columns in joins.

SQL Generator Bug fixes

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js

Fixed the checkboxes issue of going top & original position on checking/unchecking of checkboxes

Fixed the checkboxes issue of going top & original position on checking/unchecking of checkboxes

---

ModelLibrary/Model/MInvoice.cs
ModelLibrary/Model/MMovement.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/Coding%20Checklist_VAS_Above_1.5.1.0%20-%20Amit.docx?d=w4886b4da5e744f4e88fd04ce3ebfc5e7&csf=1&web=1&e=M3Mshv)
[5701](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/5701)

E-Invoicing, DevOps Task ID 5701: When IRN / E-Way bill exist then user can't be reverse the document.

---

VAS/Areas/VAS/Scripts/app/forms/VAS_TimeSheetInvoice.js
VAS/Areas/VAS/Scripts/model/CalloutCashJournal.js
VAS/Areas/VAS/Scripts/model/calloutpayment.js
VASLogic/Models/Callouts/MCashBookModel.cs
VASLogic/Models/Callouts/MInvoiceModel.cs

Handled discount amount based on discount date if applicable on below areas- 1)Payment form -Handled on check icon,cash icon,batch icon, manual icon 2)On allocate tab -when user change schedules
3)on batch window on generate button
[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/[CodingChecklist_Official_VAStandard(VAS)_Above_1.5.1.0.docx](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.5.1.0.docx?d=w9cee9cd92a8745079af10896073fe0dc&csf=1&web=1&e=HFObHG)?d=w9cee9cd92a8745079af10896073fe0dc&csf=1&web=1&e=HFObHG)
[5620](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/5620/)

DevOpsId 5620

---

ModelLibrary/Model/MElement.cs
ModelLibrary/Process/ViennaAdvantageProcess/ImportCOA.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_VAS_Above_1.5.3.0(2).docx?d=wa00e7bdee9b3457f8819aa3d72c76fe3&csf=1&web=1&e=I825JD)
[DevOps -5877](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/5877)

Added Import Process on COA window with name "COA Import"

---

VAS/Areas/VAS/Controllers/CommonController.cs
VAS/Areas/VAS/Scripts/app/forms/acctviewer.js

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/Coding%20Checklist_VAS_Above_1.5.4.0%20-%20Amit.docx?d=w54ab26584b27479e9c1778f66b4e1b3c&csf=1&web=1&e=M3OkYl)
[DevOps](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/5931)

Task ID: 5931, Handle Date Issue on Account Viewer when login with other than English Lang

---

ModelLibrary/Model/MAllocationHdr.cs
VAS/Areas/VAS/Scripts/model/calloutpayment.js

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/[CodingChecklist_Official_VAStandard(VAS)_Above_1.5.4.0.docx](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.5.4.0.docx?d=wa8518d1b5941459e88ea759bf8ed44bb&csf=1&web=1&e=QKLr9G)?d=wa8518d1b5941459e88ea759bf8ed44bb&csf=1&web=1&e=QKLr9G)

Handled Discount amt when user change currency or conversion type

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Controllers/AlertSQLGenerateController.cs
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

1. Show names suggestion instead of Ids for filtration.
2. Add where clause if exists in tab.
3. Add comparison of two columns.
[Coding Checklist](https://github.com/user-attachments/files/16064446/Coding.Checklist_NameSuggestionAddWhereClause._2July2024.docx)

Show names as suggestions for filteration in sql

---

ModelLibrary/Model/MAsset.cs
ModelLibrary/Model/MBPartner.cs
ModelLibrary/Model/MCharge.cs
ModelLibrary/Model/MProduct.cs
ModelLibrary/Model/MProductCategory.cs
ModelLibrary/Model/MTax.cs
ModelLibrary/Model/MWarehouse.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_VAS_Above_1.5.6.0(2).docx?d=w5b4a976aafd74b23bfdc0b30a6f6638e&csf=1&web=1&e=4bnctU)
[Bug ID:6004](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/6004)

Generate new sequence no. for default accounting window

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

Show suggestion for filter records
[Coding Checklist](https://github.com/user-attachments/files/16247317/Coding.Checklist_FilterSuggestion._16July2024.docx)

Show filter suggestion

---

ModelLibrary/Model/MUOMConversion.cs

[Coding CheckList](https://viennasolutions2.sharepoint.com/:w:/r/sites/SCMTechnicalTeam/Shared%20Documents/Coding%20Checklist/Coding%20Checklist%20VAS_Above_1.5.10.0_05Aug2024.docx?d=wc0a4cf9dae374733881a47b5366b8bf0&csf=1&web=1&e=hcIu0S)
[DevOps ID](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/6066)

Changes done for UOM conversion, if not exists with Product then System will check conversion from without product record.

---

VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

for createdBy & updatedBy data is not displaying issue fixes

Bug fixes (created & updated data)

---

ModelLibrary/Process/ReCostingCalculation.cs

[checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_VAS_Above_1.5.8.0(3).docx?d=wa8736285cb2f4ca697f7bb14504329fb&csf=1&web=1&e=c5Cypc)
[6102](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/6102)

Task ID: 6102 - Consider price from the Inventory line for costing when defined

---

VAS/Areas/VAS/Controllers/AlertSQLGenerateController.cs
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

1.Provide Toady's date check 
2. Fix Representative issue
[Coding Checklist](https://github.com/user-attachments/files/16958365/Coding.Checklist_ProvideTodayCheckBox._11Sep2024.docx)

Provide Toady's date check and Fix Representative issue

---

VAS/Areas/VAS/Content/PoReceiptTabPanel.css
VAS/Areas/VAS/Controllers/PoReceiptController.cs
VAS/Areas/VAS/Scripts/app/forms/VAS_ExpenseAmountWidget.js
VAS/Areas/VAS/Scripts/app/forms/VAS_InvGrandTotalWidget.js
VAS/Areas/VAS/VASAreaRegistration.cs
VAS/VAS.csproj
VASLogic/Models/PoReceiptTabPanelModel.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/[CodingChecklist_Official_VAStandard(VAS)_Above_1.5.12.0.docx](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.5.12.0.docx?d=wa7dd8f506be348cb96a4b87bc312e982&csf=1&web=1&e=2sIhcm)?d=wa7dd8f506be348cb96a4b87bc312e982&csf=1&web=1&e=2sIhcm)

Created Widget to show top 10 expense amount

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js

1. Added new functionality for getting last n days.
2. Provide delete functionality for sorting
3. Enable Disable Filter value.

Added new functionality for getting last n days And Delete functionality for sorting

---

VAS/Areas/VAS/Scripts/app/forms/vcreatefrom.js

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.5.12.0(3).docx?d=wbb44a9c598194c838eb32078fa52b6e2&csf=1&web=1&e=NyRs79)
[6189](http://130.61.149.181/ViennaAdvantage/Standard%20ERP-CRM/_workitems/edit/6189)

DevOps Bug 6189: On close of Create Line form on Invoice Screen, system will refresh the record

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Controllers/AlertSQLGenerateController.cs
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

Worked on UI fixes

---

ModelLibrary/Model/MPayment.cs
VAS/Areas/VAS/Content/PoReceiptTabPanel.css
VAS/Areas/VAS/Scripts/model/CalloutCashJournal.js
VAS/Areas/VAS/Scripts/model/calloutpayment.js

Earlier System was not allowing users to select Invoice of other currency which is selected on Payment Header on Allocate Tab Now Handled the issue and now user can select invoice other then header currency and the amount will also be converted according to it.
[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.5.12.0%20(1).docx?d=wb44e8c726f9e442c969ec78d73584b10&csf=1&web=1&e=pKoEsr)
[6192](http://130.61.149.181/ViennaAdvantage/_search?text=6192&type=workitem&lp=custom-Collection)

BugId: 6192

---

VAS/Areas/VAS/Content/PoReceiptTabPanel.css
VAS/Areas/VAS/Controllers/PoReceiptController.cs
VAS/Areas/VAS/Scripts/app/forms/VAS_ExpectedPayments.js
VAS/Areas/VAS/VASAreaRegistration.cs
VAS/VAS.csproj
VASLogic/Models/PoReceiptTabPanelModel.cs

Created Expected Payment widget against order and invoices

---

VAS/Areas/VAS/Content/PoReceiptTabPanel.css
VAS/Areas/VAS/Scripts/app/forms/VAS_ExpectedPayments.js
VAS/Areas/VAS/Scripts/model/CalloutChartOfAccount.js
VAS/Areas/VAS/VASAreaRegistration.cs
VAS/VAS.csproj
VASLogic/Models/PoReceiptTabPanelModel.cs

[Coding Checklist](https://viennasolutions2.sharepoint.com/:w:/r/sites/FinanceTechnicalTeam/Shared%20Documents/Coding%20Checklist/CodingChecklist_Official_VAStandard(VAS)_Above_1.5.12.0%20(6).docx?d=wc6c8c30c209e494787ebbea276889313&csf=1&web=1&e=vpVX9x)

Created callout to clear the bank and foreign currency details

---

VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

Worked on Sorting in Add Sort section. Also worked on Edit functionality

Worked on Sorting in Add Sort section. Also worked on Edit functionality

---

ModelLibrary/Model/MBankStatement.cs

System will not allow to void the transaction if any record found of after the min statementline date of the current Transaction. Also, system will reverse the impact on Bank Account Line

On bank Statement, System will not allow to void the transaction if any record found of after the min statementline date of the current Transaction. 

---

VAS/Areas/VAS/Scripts/app/forms/VAS_ExpectedInvoiceWidget.js
VAS/Areas/VAS/Scripts/app/forms/VAS_ExpectedPayments.js
VAS/Areas/VAS/Scripts/app/forms/acctviewer.js
VASLogic/Models/PoReceiptTabPanelModel.cs

1)fixed the format of date on expected invoice and expected payment widget. 2)Added Trunc in query to consider end dates records in total receivable widget. 3)handeld to show amount based on culture in account viewer form. 4)divided the amount from ordered quantity to get correct amount in expected amount widget.

Handled below points-

---

ModelLibrary/Model/MInvoice.cs
VASLogic/Models/PoReceiptTabPanelModel.cs

1)work done to get correct amount of order when multiple grn and invoices are created 2)handled to set ReversalDoc_ID on invoice and invoiceline on reverse of invoice

Handled Below point-

---

ModelLibrary/Model/MExpectedCost.cs
ModelLibrary/Model/MInOutConfirm.cs
ModelLibrary/Model/MMovementConfirm.cs

2.Set Target qty and difference qty after Material completion

1.Done changes for Expected land cost tab currency converison.

---

ModelLibrary/Model/MCostQueue.cs
ModelLibrary/Model/MInventory.cs
ModelLibrary/Process/ReCostingCalculation.cs

System will create Cost Queue with Movement Date as Queue Date with Current timestamp. Also, during consumption, system will consume  queue whose Queue Date is less than equal to Movement Date (In Case of LIFO)

Handle LIFO / FIFO Cost Queue case

---

ModelLibrary/Acct/FactLine.cs
ModelLibrary/Classes/CostingCheck.cs
ModelLibrary/Model/MInvoice.cs
ModelLibrary/Process/ReCostingCalculation.cs

2. Resolve Issue of COGS Adjustment in case of Treat as Discount
3. Resolve Issue of Consume Qty on Matched Invoice
4. Resolve Issue of Insert Cost Closing Process
5. Resolve Issue of Re-Costing calculation with DateFrom Parameter

1. Resolve issue of GL journal Posting for Segment Balance

---

ModelLibrary/Model/MCostQueue.cs
ModelLibrary/Model/MInOut.cs
ModelLibrary/Model/MInvoice.cs
ModelLibrary/Model/MMatchInv.cs

2. When GRN from Invoice, then on Match Invoice Differece Price of APPO will be adjusted as ZERO.
3. When Invoice created with Independent Invoice reference and Price of Invoice and Cost of GRN is differenet then on Match Invoice Differece Price of APPO will be adjusted.
4. On AP Invoice ereversal, system wil check if any treat as Discount record avaulable with Original Invoice reference then user can not reverse the Original Document.

1. Current Cost not updated on cost Queue when Current Qty iz ZERO.

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

Worked on Editing Data Field/Column which is disabled before

Worked on Editing Data Field/Column which is disabled before

---

VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

Worked on fixing Add Condition button not working issue

Worked on fixing Add Condition button not working issue

---

VAS/Areas/VAS/Content/style.css
VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js
VASLogic/Models/AlertSqlGenerate.cs

Worked on fixing the Add Sort section functionality issue

Worked on fixing the Add Sort section functionality issue

---

VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js

Remove the template literals & used + + for appending the code in add sort

Remove the template literals & used + + for appending the code in add sort

---

VAS/Areas/VAS/Scripts/app/forms/TabAlertRuleSql.js

Fixed the sorting issue in case of subbquery

Fixed the sorting issue in case of subbquery

---

VAS/Areas/VAS/Scripts/model/calloutinvoice.js
VASLogic/Models/Callouts/MBPartnerModel.cs

Set the value of supply type on change of business partner in

---

ModelLibrary/Model/MInvoice.cs
ModelLibrary/Model/MInvoiceLine.cs
ModelLibrary/Process/ViennaAdvantageProcess/InOutCreateInvoice.cs
ModelLibrary/Process/ViennaAdvantageProcess/InvoiceGenerate.cs
VAS/Areas/VAS/Scripts/app/forms/VAS_InvoiceSummary.js
VAS/Areas/VAS/Scripts/model/CalloutOrder.js
VASLogic/Models/Callouts/MBPartnerModel.cs
VASLogic/Models/PoReceiptTabPanelModel.cs

Sales Order
1. Supply Type should auto fill on Business Partner Selection.
2. When user create AR Invoice using sales order, then selected Supply Type also copied.
AR Invoice
3. Resolve issue of TCS when Tax Inclusive.
4. Handle TCS tax on Invoice Summary panel

Supply Type and TCS points

---

ModelLibrary/Model/MBPartnerLocation.cs
ModelLibrary/Model/MInvoiceLine.cs

System will not check Inter / Intra state setting for tax Exempt and Zero Tax

When the BP location does not belong to India then GST Type setting will not checked.
